### ISSUE TITLE
The ssl cert variables seem not to get used

### ISSUE THREAD

**Issue by WebsiteDeveloper** [inoxio/ansible-role-ispconfig3#3]

**Comment by MartinLesser** [comment]
Pardon us for responding late. We are looking into this issue.

**Comment by MartinLesser** [comment]
The variables were not used because the creation of the certificate was removed from this project with this commit adc12f5a2d75cdfc1a9c40ea68d412103698319b . We removed all certification variables and documentation from the project (24c713f79cdafc8f5cd9bc4a17892bb73ecd0ef5).

Kind regards,
Martin
