### ISSUE TITLE
Please update docs

### ISSUE THREAD

**Issue by ArminGruner** [inoxio/ansible-role-ispconfig3#4]
Hi,
you may delete references to certbot/letsencrypt in the docs/examples, now after commit adc12f5a2d75cdfc1a9c40ea68d412103698319b

It's a bit misleading if one intends to use certbot integration, but it does not work as described..

Thanks!
Armin

**Comment by MartinLesser** [comment]
Hi,

thank you for this issue. We solved it with this commit 24c713f79cdafc8f5cd9bc4a17892bb73ecd0ef5

Kind regards,
Martin
